language: java

jdk: openjdk11

cache:
  directories:
    - ".autoconf"
    - "$HOME/.m2"

#Enable travis to use docker
services:
  - docker

#Set env variables.
env:
  global:
    - GCP_PROJECT_ID=exam-295817
    - IMAGE=gcr.io/exam-295817/helloworld
    - CLOUD_RUN_SERVICE=helloservice
    - CLOUD_RUN_REGION=us-central1
    #Disable cloud from asking us about input
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - secure: fcj7xG5jD6hlr4cszlzQCRPlPa3QikSxlbTUvBFwgTy1Svr7snI9k/hZKePw/5Lcc77zcQD8sWp0O3IjKaVufNTDokpY9iZ2I9wUYFm1MvtFlE9ZD9RnooZqFIljIyT0nh7zg56FPu21aTGpfI2/glTiyUD7HgDmN9tiOPDnWAbEF9Dq7G7u9OSp/PktWF3J3RNuu5cX2/WQfiTZNHvoDV5ME6PNkb/osU5DuifiMe6lXDP5mAcLvndffvBE78O2HedH6YFeEtuZX/0pk2/iHvB/OnAiKCLF4N/p4GmVKew0J5lqrBCjBzm4nIF/0ucfEM0+7qM/WUvqOlg6M0JY4D1m3a2AaBe0KVBHai8TXK5kcIUCpBD01sCOUThBK1bijEUjHMK5AjJHZyXIXG/SbBdg4GApHsp9CDObet04T4T6Q00tU6SyTwg5/mkxYkVbVjszgkcux3Fu0QiczMTgounwv3hJU00svwbo8WyW+ElKforSz+bGEq1sft+G3uDz268xG9/ZeQtGlKG9OH6845Z1e2xXeMJ0r7IUlubPO9pa/kVpvLrO1j+Fk2MLavxWspkIM8FH8uaCBU85LkDTuWHDulP1lGD6s4bP7d9ZrQULBhYUd1KP9yPtl2Eg8liTQcp1a/kNknULJ9yxQhSWFZCCpsS+VtjgBjGtggEU7tE=
    - secure: GnzxcGsl5Jh2tSfZFzVWPtF0cWt9EFcWH9iG+ZOTEG6tzqtkM20WQNFLyXknU53wL1px+GTuHwuuKxvAnrUa+AhZ4fMFP3aFN17Zo/ZcefWfj8i6EnbqEcXa7TOGycOKmxXJ0bqf870rrfICyH1jskmOWaPXNrHRAhrioNtzsN4pA4E/gr1x8TPNp1SUIKvvguaF5Zn3m1oUMrIUN5GIAuNYItRyHtTU3vDSOHsFKp02XY+gJkm/ulixvp8nsDlCyKuFqgXvHiiIzEa4ssi3sU2nse3ErSigKphTkCynywbVMNuUo4xd+1Dpq61JDRmR9xGJ8A7bMkXkTR0KXX3YMadDOOfnQbfAFUX7HIW0EY7/zlQNkYiFisDAYaphQCOysbuLWw4mAJsyrdonKIEq9atTDCEm5K3ZwUyNEJ9Yi/a5Rdk5VeVdkAiedVOEz0WmdkHHzJlHGk0+b8xFUchWTbGcx1ug8ZN9gMgwHXuBLDaatQWBDdJTn2tDOBkPcPguBinZ0sJZPRIjHMTnDkk/HebSUW/8g5KPZCgfdoXjekSQnFtRcfREJS7LlWZm2QrxVNVZzUUa4phi3OOg1CODGxCIHms1eNeEvpM1tmNzmLJjk6TTt1YAN/RU99eaMCncy3QdgDvvW7XKZmFc6jHljoLb0RiA3dW15DFU3a3lWXU=


before_install:
  #Google service account JSON file which is encrypted by "travis encrypt-file"
  #Travis will decrypt this and do the remaining build process
  - openssl aes-256-cbc -K $encrypted_98d237b7dbf4_key -iv $encrypted_98d237b7dbf4_iv -in google-key.json.enc -out google-key.json -d
  #Download google cloud sdk and install it
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source "$HOME/google-cloud-sdk/path.bash.inc"
  #Use the encrypted file for activating google service account.
  - gcloud auth activate-service-account --key-file=google-key.json
  - gcloud auth configure-docker
  - gcloud config set project "${GCP_PROJECT_ID}"


#Push particular branch to remote registry after tests succeeds
deploy:
  provider: script
  script: bash ./travis/docker_push
  on:
    branch: main
