language: java

jdk: openjdk11

cache:
  directories:
    - ".autoconf"
    - "$HOME/.m2"

#Enable travis to use docker
services:
  - docker

#Set env variables (Only available during build process).
env:
  global:
    - GCP_PROJECT_ID=exam-295817
    - IMAGE=gcr.io/exam-295817/helloworld
    - CLOUD_RUN_SERVICE=helloservice
    - CLOUD_RUN_REGION=us-central1
    #Disable cloud from asking us about input
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - secure: yOMmI2oXLDeiDdCUALBDuti3zBsVgQ3zQ/DZA5cZKaIXBunj0KDXH9usQC57wesW5fpB/gNr7/+Zsrxk5uIaCJNETCoWYB7jL0QlVTETMTOJmIDSDlScTIHtpqJSRY31kOr1W8d2RPo6Wan0+dyYjpVG+38mpahkrOUkQq0f5yaKOC4yAcWhfRhQ9x5szXyT/Bz5XShLSKZaX99uWFO9mZSyvFRqPitXjDi1wVCIIM2Ajr1dxErJqdGeSzCon1mgi/kbccApDpLWe6ykZff6lX4Wocg2nW2udwxWKCNDMt7qpz9l/llU10gejbqGje4FboE6lX4mNOW/7oZxC1keG4ddL5OTb92VCCjfCRgc9cqnZ4UOxADXt0dfBpW2Aal5DVC2+TSWxJbGn6DTCkLXfleptwtMi/YaQg6rskB8e7rn97nhLzO4DIhM4RuU4BBJeE8P43lzxg+eULb7esLgN3LG8Tm9cyuXGZy6PhswF5X1sDhHkDRAozpTBZHkLWtUSRpEgYjSXdnZ7DQV/f95y4SxZKKT8dho3ES9E3BCBRFZ23NgpQLQGSpuro4JR6pRBYj0kbc6yHI39wwg6QclzjSyEFMkE5k474Hq7aW9e6HiP4u7FDQwrevkNRSVacXmIx9banz/ya23mAMo1U+1bmTZk3jWWyLwUgCpNveUCuc=
    - secure: GnzxcGsl5Jh2tSfZFzVWPtF0cWt9EFcWH9iG+ZOTEG6tzqtkM20WQNFLyXknU53wL1px+GTuHwuuKxvAnrUa+AhZ4fMFP3aFN17Zo/ZcefWfj8i6EnbqEcXa7TOGycOKmxXJ0bqf870rrfICyH1jskmOWaPXNrHRAhrioNtzsN4pA4E/gr1x8TPNp1SUIKvvguaF5Zn3m1oUMrIUN5GIAuNYItRyHtTU3vDSOHsFKp02XY+gJkm/ulixvp8nsDlCyKuFqgXvHiiIzEa4ssi3sU2nse3ErSigKphTkCynywbVMNuUo4xd+1Dpq61JDRmR9xGJ8A7bMkXkTR0KXX3YMadDOOfnQbfAFUX7HIW0EY7/zlQNkYiFisDAYaphQCOysbuLWw4mAJsyrdonKIEq9atTDCEm5K3ZwUyNEJ9Yi/a5Rdk5VeVdkAiedVOEz0WmdkHHzJlHGk0+b8xFUchWTbGcx1ug8ZN9gMgwHXuBLDaatQWBDdJTn2tDOBkPcPguBinZ0sJZPRIjHMTnDkk/HebSUW/8g5KPZCgfdoXjekSQnFtRcfREJS7LlWZm2QrxVNVZzUUa4phi3OOg1CODGxCIHms1eNeEvpM1tmNzmLJjk6TTt1YAN/RU99eaMCncy3QdgDvvW7XKZmFc6jHljoLb0RiA3dW15DFU3a3lWXU=


before_install:
  #Google service account JSON file which is encrypted by "travis encrypt-file"
  #Travis will decrypt this and do the remaining build process
  - openssl aes-256-cbc -K $encrypted_98d237b7dbf4_key -iv $encrypted_98d237b7dbf4_iv -in google-key.json.enc -out google-key.json -d
  #Download google cloud sdk and install it
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source "$HOME/google-cloud-sdk/path.bash.inc"
  #Use the encrypted file for activating google service account.
  - gcloud auth activate-service-account --key-file=google-key.json
  - gcloud auth configure-docker
  - gcloud config set project "${GCP_PROJECT_ID}"


#Push particular branch to remote registry after tests succeeds
deploy:
  provider: script
  script: bash ./travis/docker_push
  on:
    branch: main
